plugins {
  id 'com.android.application'
}

def localDebugKeystore = file("debug.keystore")

android {
  namespace 'com.volcengine.tls.android.demo'
  compileSdk 34
  defaultConfig {
    applicationId 'com.volcengine.tls.android.demo'
    minSdk 16
    targetSdk 34
    versionCode 1
    versionName '1.0'
    buildConfigField 'boolean', 'TLS_USE_SLF4J', 'false'
  }
  buildFeatures {
    buildConfig true
  }
  flavorDimensions "logger"
  productFlavors {
    noProvider {
      dimension "logger"
      buildConfigField 'boolean', 'TLS_USE_SLF4J', 'false'
    }
    slf4jProvider {
      dimension "logger"
      buildConfigField 'boolean', 'TLS_USE_SLF4J', 'true'
    }
  }
  signingConfigs {
    if (localDebugKeystore.exists()) {
      debug {
        storeFile localDebugKeystore
        storePassword "android"
        keyAlias "androiddebugkey"
        keyPassword "android"
      }
      release {
        storeFile localDebugKeystore
        storePassword "android"
        keyAlias "androiddebugkey"
        keyPassword "android"
      }
    }
  }
  buildTypes {
    release {
      minifyEnabled true
      shrinkResources true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
      if (localDebugKeystore.exists()) {
        signingConfig signingConfigs.release
      }
    }
    debug {
      minifyEnabled false
      shrinkResources false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
      if (localDebugKeystore.exists()) {
        signingConfig signingConfigs.debug
      }
    }
  }
  packagingOptions {
    exclude 'darwin/**'
    exclude 'linux/**'
    exclude 'win/**'
    exclude 'google/protobuf/**'
    pickFirst 'com/volcengine/version'
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  noProviderImplementation project(':producer-native')
  slf4jProviderImplementation project(':producer-native')
  slf4jProviderImplementation project(':logger-spi')
  slf4jProviderImplementation 'org.slf4j:slf4j-api:1.7.36'
  slf4jProviderImplementation 'org.slf4j:slf4j-simple:1.7.36'
  testImplementation 'junit:junit:4.13.2'
}
