#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root_dir"

# Reuse the classpath file generated by android-example (assuming it has all necessary deps)
# If not, we might need to add junit.
if [ ! -f android-example/.classpath.txt ]; then
    echo "Please run android-example/run-producer-demo.sh first to generate classpath."
    exit 1
fi

CP="$(cat android-example/.classpath.txt)"
# Add JUnit to classpath if not present (though our main method doesn't strictly need it to run the logic, but the class imports it)
# We can just mock it or rely on it being in the CP if android-example used it? 
# android-example pom.xml has junit scope=compile. So it should be in CP.

SDK_CLASSES="android-example/target/sdk_classes"
TEST_CLASSES="tls-android-modules/producer/build/classes/java/test_manual"

mkdir -p "$TEST_CLASSES"

echo "[INFO] Compiling PureJavaProducerTest"
javac -encoding UTF-8 -cp "$CP:$SDK_CLASSES" -d "$TEST_CLASSES" \
    tls-android-modules/producer/src/test/java/com/volcengine/tls/demo/PureJavaProducerTest.java

echo "[INFO] Running PureJavaProducerTest"
java -cp "$CP:$SDK_CLASSES:$TEST_CLASSES" com.volcengine.tls.demo.PureJavaProducerTest
