<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.volcengine-tls</groupId>
  <artifactId>tls-android-sdk-central-publish</artifactId>
  <version>2.0.3</version>
  <packaging>pom</packaging>
  <name>tls-android-sdk-central-publish</name>
  <description>Publish helper project for Volcengine TLS Android SDK</description>
  <url>https://github.com/volcengine/ve-tls-android-sdk</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <url>https://github.com/volcengine/ve-tls-android-sdk</url>
    <connection>scm:git:https://github.com/volcengine/ve-tls-android-sdk.git</connection>
    <developerConnection>scm:git:https://github.com/volcengine/ve-tls-android-sdk.git</developerConnection>
  </scm>

  <developers>
    <developer>
      <id>volcproducts</id>
      <name>VOLC TLS ANDROID SDK</name>
    </developer>
  </developers>

  <modules>
    <module>core</module>
    <module>producer</module>
    <module>full</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
</project>
