// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: putlog.proto

package com.volcengine.model.tls.pb;

public final class PutLogRequest {
  private PutLogRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LogContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.LogContent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string Key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string Key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string Value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string Value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.LogContent}
   */
  public  static final class LogContent extends
      com.google.protobuf.GeneratedMessageLite<
          LogContent, LogContent.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.LogContent)
      LogContentOrBuilder {
    private LogContent() {
      key_ = "";
      value_ = "";
    }
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.String key_;
    /**
     * <code>string Key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return key_;
    }
    /**
     * <code>string Key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(key_);
    }
    /**
     * <code>string Key = 1;</code>
     * @param value The key to set.
     */
    private void setKey(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      key_ = value;
    }
    /**
     * <code>string Key = 1;</code>
     */
    private void clearKey() {

      key_ = getDefaultInstance().getKey();
    }
    /**
     * <code>string Key = 1;</code>
     * @param value The bytes for key to set.
     */
    private void setKeyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      key_ = value.toStringUtf8();

    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.String value_;
    /**
     * <code>string Value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string Value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string Value = 2;</code>
     * @param value The value to set.
     */
    private void setValue(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      value_ = value;
    }
    /**
     * <code>string Value = 2;</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string Value = 2;</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.PutLogRequest.LogContent prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.LogContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.PutLogRequest.LogContent, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.LogContent)
        com.volcengine.model.tls.pb.PutLogRequest.LogContentOrBuilder {
      // Construct using com.volcengine.model.tls.pb.PutLogRequest.LogContent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string Key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        return instance.getKey();
      }
      /**
       * <code>string Key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return instance.getKeyBytes();
      }
      /**
       * <code>string Key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        copyOnWrite();
        instance.setKey(value);
        return this;
      }
      /**
       * <code>string Key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        copyOnWrite();
        instance.clearKey();
        return this;
      }
      /**
       * <code>string Key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyBytes(value);
        return this;
      }

      /**
       * <code>string Value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string Value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string Value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string Value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string Value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.LogContent)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.PutLogRequest.LogContent();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "key_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.PutLogRequest.LogContent> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.PutLogRequest.LogContent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.PutLogRequest.LogContent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.LogContent)
    private static final com.volcengine.model.tls.pb.PutLogRequest.LogContent DEFAULT_INSTANCE;
    static {
      LogContent defaultInstance = new LogContent();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogContent.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogContent> PARSER;

    public static com.google.protobuf.Parser<LogContent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.Log)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 Time = 1;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogContent> 
        getContentsList();
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    com.volcengine.model.tls.pb.PutLogRequest.LogContent getContents(int index);
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    int getContentsCount();

    /**
     * <code>fixed32 TimeNs = 3;</code>
     * @return Whether the timeNs field is set.
     */
    boolean hasTimeNs();
    /**
     * <code>fixed32 TimeNs = 3;</code>
     * @return The timeNs.
     */
    int getTimeNs();

    public com.volcengine.model.tls.pb.PutLogRequest.Log.OptionalTimeNsCase getOptionalTimeNsCase();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.Log}
   */
  public  static final class Log extends
      com.google.protobuf.GeneratedMessageLite<
          Log, Log.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.Log)
      LogOrBuilder {
    private Log() {
      contents_ = emptyProtobufList();
    }
    private int optionalTimeNsCase_ = 0;
    private java.lang.Object optionalTimeNs_;
    public enum OptionalTimeNsCase {
      TIMENS(3),
      OPTIONALTIMENS_NOT_SET(0);
      private final int value;
      private OptionalTimeNsCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OptionalTimeNsCase valueOf(int value) {
        return forNumber(value);
      }

      public static OptionalTimeNsCase forNumber(int value) {
        switch (value) {
          case 3: return TIMENS;
          case 0: return OPTIONALTIMENS_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public OptionalTimeNsCase
    getOptionalTimeNsCase() {
      return OptionalTimeNsCase.forNumber(
          optionalTimeNsCase_);
    }

    private void clearOptionalTimeNs() {
      optionalTimeNsCase_ = 0;
      optionalTimeNs_ = null;
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>int64 Time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 Time = 1;</code>
     * @param value The time to set.
     */
    private void setTime(long value) {
      
      time_ = value;
    }
    /**
     * <code>int64 Time = 1;</code>
     */
    private void clearTime() {

      time_ = 0L;
    }

    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.LogContent> contents_;
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogContent> getContentsList() {
      return contents_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    public java.util.List<? extends com.volcengine.model.tls.pb.PutLogRequest.LogContentOrBuilder> 
        getContentsOrBuilderList() {
      return contents_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    @java.lang.Override
    public int getContentsCount() {
      return contents_.size();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    @java.lang.Override
    public com.volcengine.model.tls.pb.PutLogRequest.LogContent getContents(int index) {
      return contents_.get(index);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    public com.volcengine.model.tls.pb.PutLogRequest.LogContentOrBuilder getContentsOrBuilder(
        int index) {
      return contents_.get(index);
    }
    private void ensureContentsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.LogContent> tmp = contents_;
      if (!tmp.isModifiable()) {
        contents_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    private void setContents(
        int index, com.volcengine.model.tls.pb.PutLogRequest.LogContent value) {
      value.getClass();
  ensureContentsIsMutable();
      contents_.set(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    private void addContents(com.volcengine.model.tls.pb.PutLogRequest.LogContent value) {
      value.getClass();
  ensureContentsIsMutable();
      contents_.add(value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    private void addContents(
        int index, com.volcengine.model.tls.pb.PutLogRequest.LogContent value) {
      value.getClass();
  ensureContentsIsMutable();
      contents_.add(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    private void addAllContents(
        java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.LogContent> values) {
      ensureContentsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, contents_);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    private void clearContents() {
      contents_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
     */
    private void removeContents(int index) {
      ensureContentsIsMutable();
      contents_.remove(index);
    }

    public static final int TIMENS_FIELD_NUMBER = 3;
    /**
     * <code>fixed32 TimeNs = 3;</code>
     * @return Whether the timeNs field is set.
     */
    @java.lang.Override
    public boolean hasTimeNs() {
      return optionalTimeNsCase_ == 3;
    }
    /**
     * <code>fixed32 TimeNs = 3;</code>
     * @return The timeNs.
     */
    @java.lang.Override
    public int getTimeNs() {
      if (optionalTimeNsCase_ == 3) {
        return (java.lang.Integer) optionalTimeNs_;
      }
      return 0;
    }
    /**
     * <code>fixed32 TimeNs = 3;</code>
     * @param value The timeNs to set.
     */
    private void setTimeNs(int value) {
      optionalTimeNsCase_ = 3;
      optionalTimeNs_ = value;
    }
    /**
     * <code>fixed32 TimeNs = 3;</code>
     */
    private void clearTimeNs() {
      if (optionalTimeNsCase_ == 3) {
        optionalTimeNsCase_ = 0;
        optionalTimeNs_ = null;
      }
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.PutLogRequest.Log prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.Log}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.PutLogRequest.Log, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.Log)
        com.volcengine.model.tls.pb.PutLogRequest.LogOrBuilder {
      // Construct using com.volcengine.model.tls.pb.PutLogRequest.Log.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public OptionalTimeNsCase
          getOptionalTimeNsCase() {
        return instance.getOptionalTimeNsCase();
      }

      public Builder clearOptionalTimeNs() {
        copyOnWrite();
        instance.clearOptionalTimeNs();
        return this;
      }


      /**
       * <code>int64 Time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return instance.getTime();
      }
      /**
       * <code>int64 Time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>int64 Time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      @java.lang.Override
      public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogContent> getContentsList() {
        return java.util.Collections.unmodifiableList(
            instance.getContentsList());
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      @java.lang.Override
      public int getContentsCount() {
        return instance.getContentsCount();
      }/**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      @java.lang.Override
      public com.volcengine.model.tls.pb.PutLogRequest.LogContent getContents(int index) {
        return instance.getContents(index);
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder setContents(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogContent value) {
        copyOnWrite();
        instance.setContents(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder setContents(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogContent.Builder builderForValue) {
        copyOnWrite();
        instance.setContents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder addContents(com.volcengine.model.tls.pb.PutLogRequest.LogContent value) {
        copyOnWrite();
        instance.addContents(value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder addContents(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogContent value) {
        copyOnWrite();
        instance.addContents(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder addContents(
          com.volcengine.model.tls.pb.PutLogRequest.LogContent.Builder builderForValue) {
        copyOnWrite();
        instance.addContents(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder addContents(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogContent.Builder builderForValue) {
        copyOnWrite();
        instance.addContents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder addAllContents(
          java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.LogContent> values) {
        copyOnWrite();
        instance.addAllContents(values);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder clearContents() {
        copyOnWrite();
        instance.clearContents();
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogContent Contents = 2;</code>
       */
      public Builder removeContents(int index) {
        copyOnWrite();
        instance.removeContents(index);
        return this;
      }

      /**
       * <code>fixed32 TimeNs = 3;</code>
       * @return Whether the timeNs field is set.
       */
      @java.lang.Override
      public boolean hasTimeNs() {
        return instance.hasTimeNs();
      }
      /**
       * <code>fixed32 TimeNs = 3;</code>
       * @return The timeNs.
       */
      @java.lang.Override
      public int getTimeNs() {
        return instance.getTimeNs();
      }
      /**
       * <code>fixed32 TimeNs = 3;</code>
       * @param value The timeNs to set.
       * @return This builder for chaining.
       */
      public Builder setTimeNs(int value) {
        copyOnWrite();
        instance.setTimeNs(value);
        return this;
      }
      /**
       * <code>fixed32 TimeNs = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeNs() {
        copyOnWrite();
        instance.clearTimeNs();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.Log)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.PutLogRequest.Log();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "optionalTimeNs_",
              "optionalTimeNsCase_",
              "time_",
              "contents_",
              com.volcengine.model.tls.pb.PutLogRequest.LogContent.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0002\u0002\u001b" +
                "\u00039\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.PutLogRequest.Log> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.PutLogRequest.Log.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.PutLogRequest.Log>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.Log)
    private static final com.volcengine.model.tls.pb.PutLogRequest.Log DEFAULT_INSTANCE;
    static {
      Log defaultInstance = new Log();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Log.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.Log getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Log> PARSER;

    public static com.google.protobuf.Parser<Log> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogTagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.LogTag)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string Key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string Key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string Value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string Value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.LogTag}
   */
  public  static final class LogTag extends
      com.google.protobuf.GeneratedMessageLite<
          LogTag, LogTag.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.LogTag)
      LogTagOrBuilder {
    private LogTag() {
      key_ = "";
      value_ = "";
    }
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.String key_;
    /**
     * <code>string Key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return key_;
    }
    /**
     * <code>string Key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(key_);
    }
    /**
     * <code>string Key = 1;</code>
     * @param value The key to set.
     */
    private void setKey(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      key_ = value;
    }
    /**
     * <code>string Key = 1;</code>
     */
    private void clearKey() {

      key_ = getDefaultInstance().getKey();
    }
    /**
     * <code>string Key = 1;</code>
     * @param value The bytes for key to set.
     */
    private void setKeyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      key_ = value.toStringUtf8();

    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.String value_;
    /**
     * <code>string Value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string Value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string Value = 2;</code>
     * @param value The value to set.
     */
    private void setValue(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      value_ = value;
    }
    /**
     * <code>string Value = 2;</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string Value = 2;</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.PutLogRequest.LogTag prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.LogTag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.PutLogRequest.LogTag, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.LogTag)
        com.volcengine.model.tls.pb.PutLogRequest.LogTagOrBuilder {
      // Construct using com.volcengine.model.tls.pb.PutLogRequest.LogTag.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string Key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        return instance.getKey();
      }
      /**
       * <code>string Key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return instance.getKeyBytes();
      }
      /**
       * <code>string Key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        copyOnWrite();
        instance.setKey(value);
        return this;
      }
      /**
       * <code>string Key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        copyOnWrite();
        instance.clearKey();
        return this;
      }
      /**
       * <code>string Key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyBytes(value);
        return this;
      }

      /**
       * <code>string Value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string Value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string Value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string Value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string Value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.LogTag)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.PutLogRequest.LogTag();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "key_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.PutLogRequest.LogTag> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.PutLogRequest.LogTag.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.PutLogRequest.LogTag>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.LogTag)
    private static final com.volcengine.model.tls.pb.PutLogRequest.LogTag DEFAULT_INSTANCE;
    static {
      LogTag defaultInstance = new LogTag();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogTag.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogTag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogTag> PARSER;

    public static com.google.protobuf.Parser<LogTag> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.LogGroup)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    java.util.List<com.volcengine.model.tls.pb.PutLogRequest.Log> 
        getLogsList();
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    com.volcengine.model.tls.pb.PutLogRequest.Log getLogs(int index);
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    int getLogsCount();

    /**
     * <code>string Source = 2;</code>
     * @return The source.
     */
    java.lang.String getSource();
    /**
     * <code>string Source = 2;</code>
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogTag> 
        getLogTagsList();
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    com.volcengine.model.tls.pb.PutLogRequest.LogTag getLogTags(int index);
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    int getLogTagsCount();

    /**
     * <code>string FileName = 4;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string FileName = 4;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string ContextFlow = 5;</code>
     * @return The contextFlow.
     */
    java.lang.String getContextFlow();
    /**
     * <code>string ContextFlow = 5;</code>
     * @return The bytes for contextFlow.
     */
    com.google.protobuf.ByteString
        getContextFlowBytes();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.LogGroup}
   */
  public  static final class LogGroup extends
      com.google.protobuf.GeneratedMessageLite<
          LogGroup, LogGroup.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.LogGroup)
      LogGroupOrBuilder {
    private LogGroup() {
      logs_ = emptyProtobufList();
      source_ = "";
      logTags_ = emptyProtobufList();
      fileName_ = "";
      contextFlow_ = "";
    }
    public static final int LOGS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.Log> logs_;
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.Log> getLogsList() {
      return logs_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    public java.util.List<? extends com.volcengine.model.tls.pb.PutLogRequest.LogOrBuilder> 
        getLogsOrBuilderList() {
      return logs_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    @java.lang.Override
    public int getLogsCount() {
      return logs_.size();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    @java.lang.Override
    public com.volcengine.model.tls.pb.PutLogRequest.Log getLogs(int index) {
      return logs_.get(index);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    public com.volcengine.model.tls.pb.PutLogRequest.LogOrBuilder getLogsOrBuilder(
        int index) {
      return logs_.get(index);
    }
    private void ensureLogsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.Log> tmp = logs_;
      if (!tmp.isModifiable()) {
        logs_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    private void setLogs(
        int index, com.volcengine.model.tls.pb.PutLogRequest.Log value) {
      value.getClass();
  ensureLogsIsMutable();
      logs_.set(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    private void addLogs(com.volcengine.model.tls.pb.PutLogRequest.Log value) {
      value.getClass();
  ensureLogsIsMutable();
      logs_.add(value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    private void addLogs(
        int index, com.volcengine.model.tls.pb.PutLogRequest.Log value) {
      value.getClass();
  ensureLogsIsMutable();
      logs_.add(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    private void addAllLogs(
        java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.Log> values) {
      ensureLogsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, logs_);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    private void clearLogs() {
      logs_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
     */
    private void removeLogs(int index) {
      ensureLogsIsMutable();
      logs_.remove(index);
    }

    public static final int SOURCE_FIELD_NUMBER = 2;
    private java.lang.String source_;
    /**
     * <code>string Source = 2;</code>
     * @return The source.
     */
    @java.lang.Override
    public java.lang.String getSource() {
      return source_;
    }
    /**
     * <code>string Source = 2;</code>
     * @return The bytes for source.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(source_);
    }
    /**
     * <code>string Source = 2;</code>
     * @param value The source to set.
     */
    private void setSource(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      source_ = value;
    }
    /**
     * <code>string Source = 2;</code>
     */
    private void clearSource() {

      source_ = getDefaultInstance().getSource();
    }
    /**
     * <code>string Source = 2;</code>
     * @param value The bytes for source to set.
     */
    private void setSourceBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      source_ = value.toStringUtf8();

    }

    public static final int LOGTAGS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.LogTag> logTags_;
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogTag> getLogTagsList() {
      return logTags_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    public java.util.List<? extends com.volcengine.model.tls.pb.PutLogRequest.LogTagOrBuilder> 
        getLogTagsOrBuilderList() {
      return logTags_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    @java.lang.Override
    public int getLogTagsCount() {
      return logTags_.size();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    @java.lang.Override
    public com.volcengine.model.tls.pb.PutLogRequest.LogTag getLogTags(int index) {
      return logTags_.get(index);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    public com.volcengine.model.tls.pb.PutLogRequest.LogTagOrBuilder getLogTagsOrBuilder(
        int index) {
      return logTags_.get(index);
    }
    private void ensureLogTagsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.LogTag> tmp = logTags_;
      if (!tmp.isModifiable()) {
        logTags_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    private void setLogTags(
        int index, com.volcengine.model.tls.pb.PutLogRequest.LogTag value) {
      value.getClass();
  ensureLogTagsIsMutable();
      logTags_.set(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    private void addLogTags(com.volcengine.model.tls.pb.PutLogRequest.LogTag value) {
      value.getClass();
  ensureLogTagsIsMutable();
      logTags_.add(value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    private void addLogTags(
        int index, com.volcengine.model.tls.pb.PutLogRequest.LogTag value) {
      value.getClass();
  ensureLogTagsIsMutable();
      logTags_.add(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    private void addAllLogTags(
        java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.LogTag> values) {
      ensureLogTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, logTags_);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    private void clearLogTags() {
      logTags_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
     */
    private void removeLogTags(int index) {
      ensureLogTagsIsMutable();
      logTags_.remove(index);
    }

    public static final int FILENAME_FIELD_NUMBER = 4;
    private java.lang.String fileName_;
    /**
     * <code>string FileName = 4;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      return fileName_;
    }
    /**
     * <code>string FileName = 4;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fileName_);
    }
    /**
     * <code>string FileName = 4;</code>
     * @param value The fileName to set.
     */
    private void setFileName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      fileName_ = value;
    }
    /**
     * <code>string FileName = 4;</code>
     */
    private void clearFileName() {

      fileName_ = getDefaultInstance().getFileName();
    }
    /**
     * <code>string FileName = 4;</code>
     * @param value The bytes for fileName to set.
     */
    private void setFileNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fileName_ = value.toStringUtf8();

    }

    public static final int CONTEXTFLOW_FIELD_NUMBER = 5;
    private java.lang.String contextFlow_;
    /**
     * <code>string ContextFlow = 5;</code>
     * @return The contextFlow.
     */
    @java.lang.Override
    public java.lang.String getContextFlow() {
      return contextFlow_;
    }
    /**
     * <code>string ContextFlow = 5;</code>
     * @return The bytes for contextFlow.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContextFlowBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contextFlow_);
    }
    /**
     * <code>string ContextFlow = 5;</code>
     * @param value The contextFlow to set.
     */
    private void setContextFlow(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      contextFlow_ = value;
    }
    /**
     * <code>string ContextFlow = 5;</code>
     */
    private void clearContextFlow() {

      contextFlow_ = getDefaultInstance().getContextFlow();
    }
    /**
     * <code>string ContextFlow = 5;</code>
     * @param value The bytes for contextFlow to set.
     */
    private void setContextFlowBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      contextFlow_ = value.toStringUtf8();

    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.PutLogRequest.LogGroup prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.LogGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.PutLogRequest.LogGroup, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.LogGroup)
        com.volcengine.model.tls.pb.PutLogRequest.LogGroupOrBuilder {
      // Construct using com.volcengine.model.tls.pb.PutLogRequest.LogGroup.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.Log> getLogsList() {
        return java.util.Collections.unmodifiableList(
            instance.getLogsList());
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      @java.lang.Override
      public int getLogsCount() {
        return instance.getLogsCount();
      }/**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      @java.lang.Override
      public com.volcengine.model.tls.pb.PutLogRequest.Log getLogs(int index) {
        return instance.getLogs(index);
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder setLogs(
          int index, com.volcengine.model.tls.pb.PutLogRequest.Log value) {
        copyOnWrite();
        instance.setLogs(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder setLogs(
          int index, com.volcengine.model.tls.pb.PutLogRequest.Log.Builder builderForValue) {
        copyOnWrite();
        instance.setLogs(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder addLogs(com.volcengine.model.tls.pb.PutLogRequest.Log value) {
        copyOnWrite();
        instance.addLogs(value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder addLogs(
          int index, com.volcengine.model.tls.pb.PutLogRequest.Log value) {
        copyOnWrite();
        instance.addLogs(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder addLogs(
          com.volcengine.model.tls.pb.PutLogRequest.Log.Builder builderForValue) {
        copyOnWrite();
        instance.addLogs(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder addLogs(
          int index, com.volcengine.model.tls.pb.PutLogRequest.Log.Builder builderForValue) {
        copyOnWrite();
        instance.addLogs(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder addAllLogs(
          java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.Log> values) {
        copyOnWrite();
        instance.addAllLogs(values);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder clearLogs() {
        copyOnWrite();
        instance.clearLogs();
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.Log Logs = 1;</code>
       */
      public Builder removeLogs(int index) {
        copyOnWrite();
        instance.removeLogs(index);
        return this;
      }

      /**
       * <code>string Source = 2;</code>
       * @return The source.
       */
      @java.lang.Override
      public java.lang.String getSource() {
        return instance.getSource();
      }
      /**
       * <code>string Source = 2;</code>
       * @return The bytes for source.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSourceBytes() {
        return instance.getSourceBytes();
      }
      /**
       * <code>string Source = 2;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          java.lang.String value) {
        copyOnWrite();
        instance.setSource(value);
        return this;
      }
      /**
       * <code>string Source = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        copyOnWrite();
        instance.clearSource();
        return this;
      }
      /**
       * <code>string Source = 2;</code>
       * @param value The bytes for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSourceBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogTag> getLogTagsList() {
        return java.util.Collections.unmodifiableList(
            instance.getLogTagsList());
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      @java.lang.Override
      public int getLogTagsCount() {
        return instance.getLogTagsCount();
      }/**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      @java.lang.Override
      public com.volcengine.model.tls.pb.PutLogRequest.LogTag getLogTags(int index) {
        return instance.getLogTags(index);
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder setLogTags(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogTag value) {
        copyOnWrite();
        instance.setLogTags(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder setLogTags(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogTag.Builder builderForValue) {
        copyOnWrite();
        instance.setLogTags(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder addLogTags(com.volcengine.model.tls.pb.PutLogRequest.LogTag value) {
        copyOnWrite();
        instance.addLogTags(value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder addLogTags(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogTag value) {
        copyOnWrite();
        instance.addLogTags(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder addLogTags(
          com.volcengine.model.tls.pb.PutLogRequest.LogTag.Builder builderForValue) {
        copyOnWrite();
        instance.addLogTags(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder addLogTags(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogTag.Builder builderForValue) {
        copyOnWrite();
        instance.addLogTags(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder addAllLogTags(
          java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.LogTag> values) {
        copyOnWrite();
        instance.addAllLogTags(values);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder clearLogTags() {
        copyOnWrite();
        instance.clearLogTags();
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogTag LogTags = 3;</code>
       */
      public Builder removeLogTags(int index) {
        copyOnWrite();
        instance.removeLogTags(index);
        return this;
      }

      /**
       * <code>string FileName = 4;</code>
       * @return The fileName.
       */
      @java.lang.Override
      public java.lang.String getFileName() {
        return instance.getFileName();
      }
      /**
       * <code>string FileName = 4;</code>
       * @return The bytes for fileName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        return instance.getFileNameBytes();
      }
      /**
       * <code>string FileName = 4;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        copyOnWrite();
        instance.setFileName(value);
        return this;
      }
      /**
       * <code>string FileName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        copyOnWrite();
        instance.clearFileName();
        return this;
      }
      /**
       * <code>string FileName = 4;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFileNameBytes(value);
        return this;
      }

      /**
       * <code>string ContextFlow = 5;</code>
       * @return The contextFlow.
       */
      @java.lang.Override
      public java.lang.String getContextFlow() {
        return instance.getContextFlow();
      }
      /**
       * <code>string ContextFlow = 5;</code>
       * @return The bytes for contextFlow.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getContextFlowBytes() {
        return instance.getContextFlowBytes();
      }
      /**
       * <code>string ContextFlow = 5;</code>
       * @param value The contextFlow to set.
       * @return This builder for chaining.
       */
      public Builder setContextFlow(
          java.lang.String value) {
        copyOnWrite();
        instance.setContextFlow(value);
        return this;
      }
      /**
       * <code>string ContextFlow = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearContextFlow() {
        copyOnWrite();
        instance.clearContextFlow();
        return this;
      }
      /**
       * <code>string ContextFlow = 5;</code>
       * @param value The bytes for contextFlow to set.
       * @return This builder for chaining.
       */
      public Builder setContextFlowBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContextFlowBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.LogGroup)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.PutLogRequest.LogGroup();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "logs_",
              com.volcengine.model.tls.pb.PutLogRequest.Log.class,
              "source_",
              "logTags_",
              com.volcengine.model.tls.pb.PutLogRequest.LogTag.class,
              "fileName_",
              "contextFlow_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0002\u0000\u0001\u001b\u0002\u0208" +
                "\u0003\u001b\u0004\u0208\u0005\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.PutLogRequest.LogGroup> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.PutLogRequest.LogGroup.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.PutLogRequest.LogGroup>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.LogGroup)
    private static final com.volcengine.model.tls.pb.PutLogRequest.LogGroup DEFAULT_INSTANCE;
    static {
      LogGroup defaultInstance = new LogGroup();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogGroup.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogGroup> PARSER;

    public static com.google.protobuf.Parser<LogGroup> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogGroupListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.LogGroupList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogGroup> 
        getLogGroupsList();
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    com.volcengine.model.tls.pb.PutLogRequest.LogGroup getLogGroups(int index);
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    int getLogGroupsCount();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.LogGroupList}
   */
  public  static final class LogGroupList extends
      com.google.protobuf.GeneratedMessageLite<
          LogGroupList, LogGroupList.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.LogGroupList)
      LogGroupListOrBuilder {
    private LogGroupList() {
      logGroups_ = emptyProtobufList();
    }
    public static final int LOGGROUPS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.LogGroup> logGroups_;
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogGroup> getLogGroupsList() {
      return logGroups_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    public java.util.List<? extends com.volcengine.model.tls.pb.PutLogRequest.LogGroupOrBuilder> 
        getLogGroupsOrBuilderList() {
      return logGroups_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    @java.lang.Override
    public int getLogGroupsCount() {
      return logGroups_.size();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    @java.lang.Override
    public com.volcengine.model.tls.pb.PutLogRequest.LogGroup getLogGroups(int index) {
      return logGroups_.get(index);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    public com.volcengine.model.tls.pb.PutLogRequest.LogGroupOrBuilder getLogGroupsOrBuilder(
        int index) {
      return logGroups_.get(index);
    }
    private void ensureLogGroupsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.PutLogRequest.LogGroup> tmp = logGroups_;
      if (!tmp.isModifiable()) {
        logGroups_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    private void setLogGroups(
        int index, com.volcengine.model.tls.pb.PutLogRequest.LogGroup value) {
      value.getClass();
  ensureLogGroupsIsMutable();
      logGroups_.set(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    private void addLogGroups(com.volcengine.model.tls.pb.PutLogRequest.LogGroup value) {
      value.getClass();
  ensureLogGroupsIsMutable();
      logGroups_.add(value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    private void addLogGroups(
        int index, com.volcengine.model.tls.pb.PutLogRequest.LogGroup value) {
      value.getClass();
  ensureLogGroupsIsMutable();
      logGroups_.add(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    private void addAllLogGroups(
        java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.LogGroup> values) {
      ensureLogGroupsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, logGroups_);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    private void clearLogGroups() {
      logGroups_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
     */
    private void removeLogGroups(int index) {
      ensureLogGroupsIsMutable();
      logGroups_.remove(index);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.PutLogRequest.LogGroupList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.LogGroupList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.PutLogRequest.LogGroupList, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.LogGroupList)
        com.volcengine.model.tls.pb.PutLogRequest.LogGroupListOrBuilder {
      // Construct using com.volcengine.model.tls.pb.PutLogRequest.LogGroupList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.volcengine.model.tls.pb.PutLogRequest.LogGroup> getLogGroupsList() {
        return java.util.Collections.unmodifiableList(
            instance.getLogGroupsList());
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      @java.lang.Override
      public int getLogGroupsCount() {
        return instance.getLogGroupsCount();
      }/**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      @java.lang.Override
      public com.volcengine.model.tls.pb.PutLogRequest.LogGroup getLogGroups(int index) {
        return instance.getLogGroups(index);
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder setLogGroups(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogGroup value) {
        copyOnWrite();
        instance.setLogGroups(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder setLogGroups(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogGroup.Builder builderForValue) {
        copyOnWrite();
        instance.setLogGroups(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder addLogGroups(com.volcengine.model.tls.pb.PutLogRequest.LogGroup value) {
        copyOnWrite();
        instance.addLogGroups(value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder addLogGroups(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogGroup value) {
        copyOnWrite();
        instance.addLogGroups(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder addLogGroups(
          com.volcengine.model.tls.pb.PutLogRequest.LogGroup.Builder builderForValue) {
        copyOnWrite();
        instance.addLogGroups(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder addLogGroups(
          int index, com.volcengine.model.tls.pb.PutLogRequest.LogGroup.Builder builderForValue) {
        copyOnWrite();
        instance.addLogGroups(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder addAllLogGroups(
          java.lang.Iterable<? extends com.volcengine.model.tls.pb.PutLogRequest.LogGroup> values) {
        copyOnWrite();
        instance.addAllLogGroups(values);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder clearLogGroups() {
        copyOnWrite();
        instance.clearLogGroups();
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.LogGroup LogGroups = 1;</code>
       */
      public Builder removeLogGroups(int index) {
        copyOnWrite();
        instance.removeLogGroups(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.LogGroupList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.PutLogRequest.LogGroupList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "logGroups_",
              com.volcengine.model.tls.pb.PutLogRequest.LogGroup.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.PutLogRequest.LogGroupList> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.PutLogRequest.LogGroupList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.PutLogRequest.LogGroupList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.LogGroupList)
    private static final com.volcengine.model.tls.pb.PutLogRequest.LogGroupList DEFAULT_INSTANCE;
    static {
      LogGroupList defaultInstance = new LogGroupList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogGroupList.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.PutLogRequest.LogGroupList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogGroupList> PARSER;

    public static com.google.protobuf.Parser<LogGroupList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
