// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rawlog.proto

package com.volcengine.model.tls.pb;

public final class RawLog {
  private RawLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RawLogGroupListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.RawLogGroupList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 OriginLen = 1;</code>
     * @return The originLen.
     */
    int getOriginLen();

    /**
     * <code>int64 LogArriveTime = 2;</code>
     * @return The logArriveTime.
     */
    long getLogArriveTime();

    /**
     * <code>string CompressType = 3;</code>
     * @return The compressType.
     */
    java.lang.String getCompressType();
    /**
     * <code>string CompressType = 3;</code>
     * @return The bytes for compressType.
     */
    com.google.protobuf.ByteString
        getCompressTypeBytes();

    /**
     * <code>string Cursor = 4;</code>
     * @return The cursor.
     */
    java.lang.String getCursor();
    /**
     * <code>string Cursor = 4;</code>
     * @return The bytes for cursor.
     */
    com.google.protobuf.ByteString
        getCursorBytes();

    /**
     * <code>bytes Data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int32 LogCount = 6;</code>
     * @return The logCount.
     */
    int getLogCount();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.RawLogGroupList}
   */
  public  static final class RawLogGroupList extends
      com.google.protobuf.GeneratedMessageLite<
          RawLogGroupList, RawLogGroupList.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.RawLogGroupList)
      RawLogGroupListOrBuilder {
    private RawLogGroupList() {
      compressType_ = "";
      cursor_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int ORIGINLEN_FIELD_NUMBER = 1;
    private int originLen_;
    /**
     * <code>int32 OriginLen = 1;</code>
     * @return The originLen.
     */
    @java.lang.Override
    public int getOriginLen() {
      return originLen_;
    }
    /**
     * <code>int32 OriginLen = 1;</code>
     * @param value The originLen to set.
     */
    private void setOriginLen(int value) {
      
      originLen_ = value;
    }
    /**
     * <code>int32 OriginLen = 1;</code>
     */
    private void clearOriginLen() {

      originLen_ = 0;
    }

    public static final int LOGARRIVETIME_FIELD_NUMBER = 2;
    private long logArriveTime_;
    /**
     * <code>int64 LogArriveTime = 2;</code>
     * @return The logArriveTime.
     */
    @java.lang.Override
    public long getLogArriveTime() {
      return logArriveTime_;
    }
    /**
     * <code>int64 LogArriveTime = 2;</code>
     * @param value The logArriveTime to set.
     */
    private void setLogArriveTime(long value) {
      
      logArriveTime_ = value;
    }
    /**
     * <code>int64 LogArriveTime = 2;</code>
     */
    private void clearLogArriveTime() {

      logArriveTime_ = 0L;
    }

    public static final int COMPRESSTYPE_FIELD_NUMBER = 3;
    private java.lang.String compressType_;
    /**
     * <code>string CompressType = 3;</code>
     * @return The compressType.
     */
    @java.lang.Override
    public java.lang.String getCompressType() {
      return compressType_;
    }
    /**
     * <code>string CompressType = 3;</code>
     * @return The bytes for compressType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompressTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(compressType_);
    }
    /**
     * <code>string CompressType = 3;</code>
     * @param value The compressType to set.
     */
    private void setCompressType(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      compressType_ = value;
    }
    /**
     * <code>string CompressType = 3;</code>
     */
    private void clearCompressType() {

      compressType_ = getDefaultInstance().getCompressType();
    }
    /**
     * <code>string CompressType = 3;</code>
     * @param value The bytes for compressType to set.
     */
    private void setCompressTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      compressType_ = value.toStringUtf8();

    }

    public static final int CURSOR_FIELD_NUMBER = 4;
    private java.lang.String cursor_;
    /**
     * <code>string Cursor = 4;</code>
     * @return The cursor.
     */
    @java.lang.Override
    public java.lang.String getCursor() {
      return cursor_;
    }
    /**
     * <code>string Cursor = 4;</code>
     * @return The bytes for cursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCursorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cursor_);
    }
    /**
     * <code>string Cursor = 4;</code>
     * @param value The cursor to set.
     */
    private void setCursor(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      cursor_ = value;
    }
    /**
     * <code>string Cursor = 4;</code>
     */
    private void clearCursor() {

      cursor_ = getDefaultInstance().getCursor();
    }
    /**
     * <code>string Cursor = 4;</code>
     * @param value The bytes for cursor to set.
     */
    private void setCursorBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      cursor_ = value.toStringUtf8();

    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes Data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes Data = 5;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes Data = 5;</code>
     */
    private void clearData() {

      data_ = getDefaultInstance().getData();
    }

    public static final int LOGCOUNT_FIELD_NUMBER = 6;
    private int logCount_;
    /**
     * <code>int32 LogCount = 6;</code>
     * @return The logCount.
     */
    @java.lang.Override
    public int getLogCount() {
      return logCount_;
    }
    /**
     * <code>int32 LogCount = 6;</code>
     * @param value The logCount to set.
     */
    private void setLogCount(int value) {
      
      logCount_ = value;
    }
    /**
     * <code>int32 LogCount = 6;</code>
     */
    private void clearLogCount() {

      logCount_ = 0;
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.RawLog.RawLogGroupList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.RawLogGroupList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.RawLog.RawLogGroupList, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.RawLogGroupList)
        com.volcengine.model.tls.pb.RawLog.RawLogGroupListOrBuilder {
      // Construct using com.volcengine.model.tls.pb.RawLog.RawLogGroupList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 OriginLen = 1;</code>
       * @return The originLen.
       */
      @java.lang.Override
      public int getOriginLen() {
        return instance.getOriginLen();
      }
      /**
       * <code>int32 OriginLen = 1;</code>
       * @param value The originLen to set.
       * @return This builder for chaining.
       */
      public Builder setOriginLen(int value) {
        copyOnWrite();
        instance.setOriginLen(value);
        return this;
      }
      /**
       * <code>int32 OriginLen = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginLen() {
        copyOnWrite();
        instance.clearOriginLen();
        return this;
      }

      /**
       * <code>int64 LogArriveTime = 2;</code>
       * @return The logArriveTime.
       */
      @java.lang.Override
      public long getLogArriveTime() {
        return instance.getLogArriveTime();
      }
      /**
       * <code>int64 LogArriveTime = 2;</code>
       * @param value The logArriveTime to set.
       * @return This builder for chaining.
       */
      public Builder setLogArriveTime(long value) {
        copyOnWrite();
        instance.setLogArriveTime(value);
        return this;
      }
      /**
       * <code>int64 LogArriveTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogArriveTime() {
        copyOnWrite();
        instance.clearLogArriveTime();
        return this;
      }

      /**
       * <code>string CompressType = 3;</code>
       * @return The compressType.
       */
      @java.lang.Override
      public java.lang.String getCompressType() {
        return instance.getCompressType();
      }
      /**
       * <code>string CompressType = 3;</code>
       * @return The bytes for compressType.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCompressTypeBytes() {
        return instance.getCompressTypeBytes();
      }
      /**
       * <code>string CompressType = 3;</code>
       * @param value The compressType to set.
       * @return This builder for chaining.
       */
      public Builder setCompressType(
          java.lang.String value) {
        copyOnWrite();
        instance.setCompressType(value);
        return this;
      }
      /**
       * <code>string CompressType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompressType() {
        copyOnWrite();
        instance.clearCompressType();
        return this;
      }
      /**
       * <code>string CompressType = 3;</code>
       * @param value The bytes for compressType to set.
       * @return This builder for chaining.
       */
      public Builder setCompressTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCompressTypeBytes(value);
        return this;
      }

      /**
       * <code>string Cursor = 4;</code>
       * @return The cursor.
       */
      @java.lang.Override
      public java.lang.String getCursor() {
        return instance.getCursor();
      }
      /**
       * <code>string Cursor = 4;</code>
       * @return The bytes for cursor.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCursorBytes() {
        return instance.getCursorBytes();
      }
      /**
       * <code>string Cursor = 4;</code>
       * @param value The cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursor(
          java.lang.String value) {
        copyOnWrite();
        instance.setCursor(value);
        return this;
      }
      /**
       * <code>string Cursor = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCursor() {
        copyOnWrite();
        instance.clearCursor();
        return this;
      }
      /**
       * <code>string Cursor = 4;</code>
       * @param value The bytes for cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCursorBytes(value);
        return this;
      }

      /**
       * <code>bytes Data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes Data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes Data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>int32 LogCount = 6;</code>
       * @return The logCount.
       */
      @java.lang.Override
      public int getLogCount() {
        return instance.getLogCount();
      }
      /**
       * <code>int32 LogCount = 6;</code>
       * @param value The logCount to set.
       * @return This builder for chaining.
       */
      public Builder setLogCount(int value) {
        copyOnWrite();
        instance.setLogCount(value);
        return this;
      }
      /**
       * <code>int32 LogCount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogCount() {
        copyOnWrite();
        instance.clearLogCount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.RawLogGroupList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.RawLog.RawLogGroupList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "originLen_",
              "logArriveTime_",
              "compressType_",
              "cursor_",
              "data_",
              "logCount_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u0002" +
                "\u0003\u0208\u0004\u0208\u0005\n\u0006\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.RawLog.RawLogGroupList> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.RawLog.RawLogGroupList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.RawLog.RawLogGroupList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.RawLogGroupList)
    private static final com.volcengine.model.tls.pb.RawLog.RawLogGroupList DEFAULT_INSTANCE;
    static {
      RawLogGroupList defaultInstance = new RawLogGroupList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RawLogGroupList.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RawLogGroupList> PARSER;

    public static com.google.protobuf.Parser<RawLogGroupList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RawLogGroupListListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.volcengine.model.tls.pb.RawLogGroupListList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    java.util.List<com.volcengine.model.tls.pb.RawLog.RawLogGroupList> 
        getRawLogGroupListsList();
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    com.volcengine.model.tls.pb.RawLog.RawLogGroupList getRawLogGroupLists(int index);
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    int getRawLogGroupListsCount();
  }
  /**
   * Protobuf type {@code com.volcengine.model.tls.pb.RawLogGroupListList}
   */
  public  static final class RawLogGroupListList extends
      com.google.protobuf.GeneratedMessageLite<
          RawLogGroupListList, RawLogGroupListList.Builder> implements
      // @@protoc_insertion_point(message_implements:com.volcengine.model.tls.pb.RawLogGroupListList)
      RawLogGroupListListOrBuilder {
    private RawLogGroupListList() {
      rawLogGroupLists_ = emptyProtobufList();
    }
    public static final int RAWLOGGROUPLISTS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.RawLog.RawLogGroupList> rawLogGroupLists_;
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.volcengine.model.tls.pb.RawLog.RawLogGroupList> getRawLogGroupListsList() {
      return rawLogGroupLists_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    public java.util.List<? extends com.volcengine.model.tls.pb.RawLog.RawLogGroupListOrBuilder> 
        getRawLogGroupListsOrBuilderList() {
      return rawLogGroupLists_;
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    @java.lang.Override
    public int getRawLogGroupListsCount() {
      return rawLogGroupLists_.size();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    @java.lang.Override
    public com.volcengine.model.tls.pb.RawLog.RawLogGroupList getRawLogGroupLists(int index) {
      return rawLogGroupLists_.get(index);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    public com.volcengine.model.tls.pb.RawLog.RawLogGroupListOrBuilder getRawLogGroupListsOrBuilder(
        int index) {
      return rawLogGroupLists_.get(index);
    }
    private void ensureRawLogGroupListsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.volcengine.model.tls.pb.RawLog.RawLogGroupList> tmp = rawLogGroupLists_;
      if (!tmp.isModifiable()) {
        rawLogGroupLists_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    private void setRawLogGroupLists(
        int index, com.volcengine.model.tls.pb.RawLog.RawLogGroupList value) {
      value.getClass();
  ensureRawLogGroupListsIsMutable();
      rawLogGroupLists_.set(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    private void addRawLogGroupLists(com.volcengine.model.tls.pb.RawLog.RawLogGroupList value) {
      value.getClass();
  ensureRawLogGroupListsIsMutable();
      rawLogGroupLists_.add(value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    private void addRawLogGroupLists(
        int index, com.volcengine.model.tls.pb.RawLog.RawLogGroupList value) {
      value.getClass();
  ensureRawLogGroupListsIsMutable();
      rawLogGroupLists_.add(index, value);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    private void addAllRawLogGroupLists(
        java.lang.Iterable<? extends com.volcengine.model.tls.pb.RawLog.RawLogGroupList> values) {
      ensureRawLogGroupListsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, rawLogGroupLists_);
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    private void clearRawLogGroupLists() {
      rawLogGroupLists_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
     */
    private void removeRawLogGroupLists(int index) {
      ensureRawLogGroupListsIsMutable();
      rawLogGroupLists_.remove(index);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.volcengine.model.tls.pb.RawLog.RawLogGroupListList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.volcengine.model.tls.pb.RawLogGroupListList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.volcengine.model.tls.pb.RawLog.RawLogGroupListList, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.volcengine.model.tls.pb.RawLogGroupListList)
        com.volcengine.model.tls.pb.RawLog.RawLogGroupListListOrBuilder {
      // Construct using com.volcengine.model.tls.pb.RawLog.RawLogGroupListList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.volcengine.model.tls.pb.RawLog.RawLogGroupList> getRawLogGroupListsList() {
        return java.util.Collections.unmodifiableList(
            instance.getRawLogGroupListsList());
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      @java.lang.Override
      public int getRawLogGroupListsCount() {
        return instance.getRawLogGroupListsCount();
      }/**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      @java.lang.Override
      public com.volcengine.model.tls.pb.RawLog.RawLogGroupList getRawLogGroupLists(int index) {
        return instance.getRawLogGroupLists(index);
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder setRawLogGroupLists(
          int index, com.volcengine.model.tls.pb.RawLog.RawLogGroupList value) {
        copyOnWrite();
        instance.setRawLogGroupLists(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder setRawLogGroupLists(
          int index, com.volcengine.model.tls.pb.RawLog.RawLogGroupList.Builder builderForValue) {
        copyOnWrite();
        instance.setRawLogGroupLists(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder addRawLogGroupLists(com.volcengine.model.tls.pb.RawLog.RawLogGroupList value) {
        copyOnWrite();
        instance.addRawLogGroupLists(value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder addRawLogGroupLists(
          int index, com.volcengine.model.tls.pb.RawLog.RawLogGroupList value) {
        copyOnWrite();
        instance.addRawLogGroupLists(index, value);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder addRawLogGroupLists(
          com.volcengine.model.tls.pb.RawLog.RawLogGroupList.Builder builderForValue) {
        copyOnWrite();
        instance.addRawLogGroupLists(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder addRawLogGroupLists(
          int index, com.volcengine.model.tls.pb.RawLog.RawLogGroupList.Builder builderForValue) {
        copyOnWrite();
        instance.addRawLogGroupLists(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder addAllRawLogGroupLists(
          java.lang.Iterable<? extends com.volcengine.model.tls.pb.RawLog.RawLogGroupList> values) {
        copyOnWrite();
        instance.addAllRawLogGroupLists(values);
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder clearRawLogGroupLists() {
        copyOnWrite();
        instance.clearRawLogGroupLists();
        return this;
      }
      /**
       * <code>repeated .com.volcengine.model.tls.pb.RawLogGroupList RawLogGroupLists = 1;</code>
       */
      public Builder removeRawLogGroupLists(int index) {
        copyOnWrite();
        instance.removeRawLogGroupLists(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.volcengine.model.tls.pb.RawLogGroupListList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.volcengine.model.tls.pb.RawLog.RawLogGroupListList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "rawLogGroupLists_",
              com.volcengine.model.tls.pb.RawLog.RawLogGroupList.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.volcengine.model.tls.pb.RawLog.RawLogGroupListList> parser = PARSER;
          if (parser == null) {
            synchronized (com.volcengine.model.tls.pb.RawLog.RawLogGroupListList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.volcengine.model.tls.pb.RawLog.RawLogGroupListList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.volcengine.model.tls.pb.RawLogGroupListList)
    private static final com.volcengine.model.tls.pb.RawLog.RawLogGroupListList DEFAULT_INSTANCE;
    static {
      RawLogGroupListList defaultInstance = new RawLogGroupListList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RawLogGroupListList.class, defaultInstance);
    }

    public static com.volcengine.model.tls.pb.RawLog.RawLogGroupListList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RawLogGroupListList> PARSER;

    public static com.google.protobuf.Parser<RawLogGroupListList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
