-keep class com.volcengine.tls.android.producer.** { *; }
-keep class com.volcengine.tls.android.producer.model.** { *; }
-keep class com.volcengine.model.tls.producer.** { *; }
-keep class com.volcengine.service.tls.** { *; }
-keep class com.volcengine.model.tls.** { *; }
