POM_GROUP=io.github.volcengine-tls
POM_VERSION=2.0.4
POM_NAME=volc-tls-android-sdk
POM_URL=https://github.com/volcengine/ve-tls-android-sdk
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=volcproducts
POM_DEVELOPER_NAME=VOLC TLS ANDROID SDK
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
